language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"

before_script:
  - composer self-update
  - composer install --prefer-dist -o
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - php tools/scrutinizer/ocular.phar code-coverage:upload --format=php-clover coverage.clover
